// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe6CIDM_qyQbOsSTqwv8T9oTEaik2p_wg',
    appId: '1:529599316057:web:993b7c5326f593b0bc3148',
    messagingSenderId: '529599316057',
    projectId: 'sports-app-d2596',
    authDomain: 'sports-app-d2596.firebaseapp.com',
    storageBucket: 'sports-app-d2596.firebasestorage.app',
    measurementId: 'G-ZGE22HPPJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxeuSTOjoPfZ4M92i1GTXgzruprikvFDU',
    appId: '1:529599316057:android:6cf9c8204475c0d7bc3148',
    messagingSenderId: '529599316057',
    projectId: 'sports-app-d2596',
    storageBucket: 'sports-app-d2596.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRoUN4ZtLcH0QchuhXiPlBxP3Zwj_Pw8U',
    appId: '1:529599316057:ios:547a1256d74501febc3148',
    messagingSenderId: '529599316057',
    projectId: 'sports-app-d2596',
    storageBucket: 'sports-app-d2596.firebasestorage.app',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRoUN4ZtLcH0QchuhXiPlBxP3Zwj_Pw8U',
    appId: '1:529599316057:ios:547a1256d74501febc3148',
    messagingSenderId: '529599316057',
    projectId: 'sports-app-d2596',
    storageBucket: 'sports-app-d2596.firebasestorage.app',
    iosBundleId: 'com.example.sportsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe6CIDM_qyQbOsSTqwv8T9oTEaik2p_wg',
    appId: '1:529599316057:web:61d03ccfb676bcbdbc3148',
    messagingSenderId: '529599316057',
    projectId: 'sports-app-d2596',
    authDomain: 'sports-app-d2596.firebaseapp.com',
    storageBucket: 'sports-app-d2596.firebasestorage.app',
    measurementId: 'G-351Q9NSRD3',
  );

}